### ISSUE TITLE
enhance user experience with mouse wheel zooming

### ISSUE THREAD

**Issue by Ventusfahrer** [kflog-project/KFLog#10]
- zooming is very slow at the moment
- every wheel-click will increase/decrease the zoom/level by one scale.
- +10 zoom events can easily happen with one time turning the wheel

very bad user experience caused by slow performance!
(maybe one should peek events from the event queue and do only one zoom operation instead of 10).
- when mouse wheel based zooming is handeled the current mouse location on the map should also be considered to move the map center towards the mouse position.

**Comment by speed-axel** [comment]
I realized your proposal.
