### ISSUE TITLE
allow transparency on forrest

### ISSUE THREAD

**Issue by Ventusfahrer** [kflog-project/KFLog#25]
currently we can't change the transparency (opaqueness) on forrest objects (the controls are disabled).

All map elements which cover areas should allow the selection of opaqueness.

![opaqueforrest](https://cloud.githubusercontent.com/assets/5901190/4261906/a50634da-3b83-11e4-9683-4e71bbc5a91e.png)

**Comment by speed-axel** [comment]
I have realized the setting of  the transparency (opaqueness) on forrest objects in the configuration window.
