### ISSUE TITLE
All airspaces and points "not approved"

### ISSUE THREAD

**Issue by klaussnd** [kflog-project/KFLog#69]
Hi!

Thanks a lot for porting kflog to recent Qt5, the project was stalled a long time. I tried it again after several years with a clean install of the Debian package and no old data present. After some initial hickups the app correctly downloaded waypoints and airspace data, however none of them are displayed. On stdout I see:
```
"/home/klaus/fliegen/kflog/mapdata/airspaces/de_asp.json" Airspaces Json Parse result: "no error occurred"
Airspace Doc is a Json Array of size: 661
Object "'ALB-NORD_2 128.950'" contains not the approved key, ignoring data
...
```
and this `contains not the approved key, ignoring data` is repeated for every single item. The same happens for waypoints:
```
"/home/klaus/fliegen/kflog/mapdata/points/de_apt.json" Airfield Json Parse result: "no error occurred"
Airfield Doc is a Json Array of size: 1365
Object "'FLENSBURG-SONWIK'" contains not the approved key, ignoring data
...
```
and again for every single point this is repeated.

I am a bit lost what the correct user workflow would be, since all files were downloaded automatically and I would have naively expected it to "just work". I could also not find any button or other way in the UI to set anything to "approved". Looking through the code, the only place I found something related is in the reader in `kflog/OpenAip.cpp` where there are statements like
```
      // check for approval
      if( object.contains("approved") == false )
        {
          qWarning() << "Object" << "'" + name + "'"
                     << "contains not the approved key, ignoring data";
          continue;
        }
```
https://github.com/kflog-project/KFLog/blob/master/kflog/OpenAip.cpp#L161-L166
but no other mention as to how to make something approved or what this concept actually means.

What is the intended way of using this data for end users?

Thanks in advance,
Klaus

**Comment by speed-axel** [comment]
Hi Klaus,

openAIP has changed the json data format a little bit. For Cumulus I have fixed it already. In the next days I will do it also for KFLog. 

Grüße Axel

**Comment by speed-axel** [comment]
Your reported issue should be fixed. I built a new Debian package. It is to find under Releases/Debian. An Ubuntu package will be follow in the next hours.

**Comment by klaussnd** [comment]
Thanks a lot for fixing it so quickly. The build in https://github.com/kflog-project/KFLog/tree/master/Releases/Debian works for me. Note that https://github.com/kflog-project/KFLog/releases/ doesn't show 5.0.1.

**Comment by speed-axel** [comment]
I was unexpected interruped for a longer time. Release 5.0.1 should be shown now.
